name: Build ZMK Firmware

on:
  workflow_dispatch:
    inputs:
      board:
        description: 'Board'
        required: true
        type: string
        default: 'nice_nano_v2'
      shield:
        description: 'Shield'
        required: true
        type: string
        default: 'my_split_board'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          sudo apt update
          sudo apt install -y git wget python3 python3-pip cmake

      - name: Install West and Clone ZMK
        run: |
          pip3 install west
          git clone https://github.com/zmkfirmware/zmk.git zmk
          cd zmk
          west init -l app/
          west update
          west zephyr-export
          pip3 install -r zephyr/scripts/requirements.txt

      - name: Build Firmware
        run: |
          cd zmk/app
          west build -b ${{ inputs.board }} -- -DSHIELD=${{ inputs.shield }} -DZMK_CONFIG="/github/workspace/config"
          mkdir -p /github/workspace/firmware
          cp build/zephyr/zmk.uf2 /github/workspace/firmware/

      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: firmware/
          retention-days: 1
