name: Build ZMK Firmware

on:
  workflow_dispatch:
    inputs:
      board:
        description: 'Board'
        required: true
        type: string
        default: 'nice_nano_v2'
      shield:
        description: 'Shield'
        required: true
        type: string
        default: 'my_split_board'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Build
        uses: zmkfirmware/zmk/.github/actions/build@main
        with:
          board: ${{ inputs.board }}
          shield: ${{ inputs.shield }}
          config-dir: config
